#!/bin/bash
set -u

# Set default location if one is not provided through the CAPTURE_DIR env variable
__tmpdir="./.scarchive/$(date '+%m/%d')"
__tmpdir="${CAPTURE_DIR:-$__tmpdir}"
[ ! -d $__tmpdir ] && \
    echo "Warning: Directory ${__tmpdir} does not exist, creating." && \
    mkdir -p "${__tmpdir}"

# Find most recent screenshot in directory, format new incremented name
__strval=""
__newest=$(ls -t $__tmpdir | head -n1)
__intval=$(expr $(echo $__newest | cut -d. -f1) + 1)
printf -v __strval "%05d" $__intval
__path="${__tmpdir}/${__strval}.png"

__debug="${DEBUG:-}"
if [[ -n $__debug ]]; then
  echo "tmp dir:      ${__tmpdir}"
  echo "last capture: ${__newest} -> ${__intval}"
  echo "write path:   ${__path}"
  echo "comparing ${__path} to ${__tmpdir}/${__newest}"
fi

screencapture -d -x -r $__path

__dirnum=$(expr $(ls -t .scarchive/01/06/ | wc -l) + 1)
if (( $__dirnum > 10 )); then
  perceptualdiff -threshold 100 -downsample 4 $__path "${__tmpdir}/${__newest}" > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "deleting new version" && rm $__path
  fi
fi

echo $__intval
