#!/bin/bash
set -u

# Set default location if one is not provided through the CAPTURE_DIR env variable
__tmpdir="./.scarchive/$(date '+%m/%d')"
__tmpdir="${CAPTURE_DIR:-$__tmpdir}"
[ ! -d $__tmpdir ] && \
    echo "Warning: Directory ${__tmpdir} does not exist, creating." && \
    mkdir -p "${__tmpdir}"

# Find most recent screenshot in directory, format new incremented name
__strval=""
__newest=$(ls -t $__tmpdir | head -n1)
__intval=$(expr $(echo $__newest | cut -d. -f1) + 1)
printf -v __strval "%05d" $__intval
__path="${__tmpdir}/${__strval}.png"

if [[ -n $DEBUG ]]; then
  echo "tmp dir:      ${__tmpdir}"
  echo "last capture: ${__newest} -> ${__intval}"
  echo "write path:   ${__path}"
fi

screencapture -d -x -r $__path

echo $__intval
